### PR TITLE
Merge from my "master" branch

### PR DESCRIPTION
**Pull request by cooljeanius**
Is this what you meant? Or did you mean from one of my other branches to one of your other branches?

### CODE REVIEW

**Comment by talregev** [comment]
I meant a PR for upstream: 
https://github.com/gcc-mirror/gcc

**Comment by cooljeanius** [comment]
> I meant a PR for upstream: [gcc-mirror/gcc](https://github.com/gcc-mirror/gcc)

That's not actually upstream though; that's just a mirror set up by who-knows-whoever. Submitting a PR there is generally considered a waste of time.

**Comment by talregev** [comment]
~~It official mirror.~~ and all other look at this repo (and not at my repo). Like you see mine there and continue from that.

**Comment by cooljeanius** [comment]
> It official mirror.

No, it's not an official mirror. The GCC project does not maintain it and has been asking GitHub to take it down for awhile now.

**Comment by talregev** [comment]
Even it not official, people look at this. and continue PRs from there.

**Comment by cooljeanius** [comment]
> Even it not official, people look at this. and continue PRs from there.

Well they could still also look at this, too

**Comment by talregev** [comment]
I will create duplicate to my branch. 
Can you merge this to my duplicate?

**Comment by cooljeanius** [comment]
> I will create duplicate to my branch. Can you merge this to my duplicate?

Sure, just let me know which one you mean.

**Comment by talregev** [comment]
@cooljeanius 
this is the new branch
`TalR/gcc_ci_cooljeanius`

**Comment by cooljeanius** [comment]
ok I changed the base branch

**Comment by talregev** [comment]
Did you finish to develop?

**Comment by cooljeanius** [comment]
> Did you finish to develop?

I am done with this particular yaml file for now, yes. There are still some further improvements that could be made, like getting caching to work properly, or getting uploading of logfiles to work properly, but I'm not planning on focusing on either of those any more at the moment.

**Comment by talregev** [comment]
Can you create changes only the yaml file?
For other changes, we can create a different branch, with different PR.

**Comment by cooljeanius** [comment]
> Can you create changes only the yaml file? For other changes, we can create a different branch, with different PR.

All right, I think that's what my `me/CI` branch does; let me check...

**Comment by cooljeanius** [comment]
> > Can you create changes only the yaml file? For other changes, we can create a different branch, with different PR.
> 
> All right, I think that's what my `me/CI` branch does; let me check...

OK, I opened PR #4 instead.

**Pull request closed without merging**
